# Generated by Django 5.0.7 on 2024-08-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=11)),
                ("password", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
