# Generated by Django 5.0.7 on 2024-08-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0002_users_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="name",
        ),
        migrations.AddField(
            model_name="users",
            name="username",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(default="", max_length=11),
        ),
    ]
