# Generated by Django 5.0.7 on 2024-08-10 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0003_remove_users_name_users_username_alter_users_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="password",
        ),
    ]
